apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fcg

resources:
  - serviceaccounts.yaml
  - users-api-deployment.yaml
  - users-worker-deployment.yaml
  - users-api-hpa.yaml


