apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fcg

resources:
  - serviceaccounts.yaml
  - games-api-deployment.yaml
  - games-worker-deployment.yaml
  - games-api-hpa.yaml


